project:
  type: website

website:
  title: "AO1: Health-Conscious Dashboard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dashboard"
        href: dashboard.qmd
      - text: "Shiny Apps"
        href: shiny-apps.qmd
      - text: "Shinylive"
        href: shinylive.qmd


